# Generated by Django 5.1.6 on 2025-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field1", models.CharField(max_length=100)),
                ("field2", models.IntegerField()),
            ],
            options={
                "db_table": "your_nocodedb_table",
            },
        ),
        migrations.RemoveField(
            model_name="choice",
            name="choice_text",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="choice",
            name="votes",
        ),
        migrations.RemoveField(
            model_name="question",
            name="pub_date",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_text",
        ),
    ]
